version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Create google-services.json
          command: echo $GOOGLE_SERVICES | base64 --decode > ~/code/app/google-services.json
    #   - run:
    #       name: Create tmdb.xml
    #       command: echo $TMDB_CONFIG | base64 --decode > ~/code/app/src/main/res/values/tmdb.xml
      - run:
          name: Create keys.xml
          command: echo $KEYS | base64 --decode > ~/code/app/src/main/res/values/keys.xml
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
